use_frameworks!
platform :ios, '8.0'

target 'Firestore_Example' do
  pod 'FirebaseCommunity/Core', :path => '../../'
  pod 'Firestore', :path => '../', :testspecs => ['Firestore_Tests', 'Firestore_IntegrationTests']
end

target 'SwiftBuildTest' do
  pod 'Firestore', :path => '../'
end
